// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package authentik

import (
	"context"
	"reflect"

	"github.com/OSMIT-GmbH/pulumi-authentik/sdk/go/authentik/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupFlow(ctx *pulumi.Context, args *LookupFlowArgs, opts ...pulumi.InvokeOption) (*LookupFlowResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFlowResult
	err := ctx.Invoke("authentik:index/getFlow:getFlow", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFlow.
type LookupFlowArgs struct {
	Authentication *string `pulumi:"authentication"`
	Designation    *string `pulumi:"designation"`
	Slug           *string `pulumi:"slug"`
}

// A collection of values returned by getFlow.
type LookupFlowResult struct {
	Authentication string `pulumi:"authentication"`
	Designation    string `pulumi:"designation"`
	// The provider-assigned unique ID for this managed resource.
	Id    string `pulumi:"id"`
	Name  string `pulumi:"name"`
	Slug  string `pulumi:"slug"`
	Title string `pulumi:"title"`
}

func LookupFlowOutput(ctx *pulumi.Context, args LookupFlowOutputArgs, opts ...pulumi.InvokeOption) LookupFlowResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFlowResult, error) {
			args := v.(LookupFlowArgs)
			r, err := LookupFlow(ctx, &args, opts...)
			var s LookupFlowResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFlowResultOutput)
}

// A collection of arguments for invoking getFlow.
type LookupFlowOutputArgs struct {
	Authentication pulumi.StringPtrInput `pulumi:"authentication"`
	Designation    pulumi.StringPtrInput `pulumi:"designation"`
	Slug           pulumi.StringPtrInput `pulumi:"slug"`
}

func (LookupFlowOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFlowArgs)(nil)).Elem()
}

// A collection of values returned by getFlow.
type LookupFlowResultOutput struct{ *pulumi.OutputState }

func (LookupFlowResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFlowResult)(nil)).Elem()
}

func (o LookupFlowResultOutput) ToLookupFlowResultOutput() LookupFlowResultOutput {
	return o
}

func (o LookupFlowResultOutput) ToLookupFlowResultOutputWithContext(ctx context.Context) LookupFlowResultOutput {
	return o
}

func (o LookupFlowResultOutput) Authentication() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlowResult) string { return v.Authentication }).(pulumi.StringOutput)
}

func (o LookupFlowResultOutput) Designation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlowResult) string { return v.Designation }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupFlowResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlowResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFlowResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlowResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupFlowResultOutput) Slug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlowResult) string { return v.Slug }).(pulumi.StringOutput)
}

func (o LookupFlowResultOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlowResult) string { return v.Title }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFlowResultOutput{})
}
