// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package authentik

import (
	"context"
	"reflect"

	"github.com/OSMIT-GmbH/pulumi-authentik/sdk/go/authentik/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get SAML Provider metadata
func GetProviderSamlMetadata(ctx *pulumi.Context, args *GetProviderSamlMetadataArgs, opts ...pulumi.InvokeOption) (*GetProviderSamlMetadataResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProviderSamlMetadataResult
	err := ctx.Invoke("authentik:index/getProviderSamlMetadata:getProviderSamlMetadata", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProviderSamlMetadata.
type GetProviderSamlMetadataArgs struct {
	// Find provider by name
	Name *string `pulumi:"name"`
	// Find provider by ID
	ProviderId *int `pulumi:"providerId"`
}

// A collection of values returned by getProviderSamlMetadata.
type GetProviderSamlMetadataResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// SAML Metadata Generated.
	Metadata string `pulumi:"metadata"`
	// Find provider by name
	Name *string `pulumi:"name"`
	// Find provider by ID
	ProviderId *int `pulumi:"providerId"`
}

func GetProviderSamlMetadataOutput(ctx *pulumi.Context, args GetProviderSamlMetadataOutputArgs, opts ...pulumi.InvokeOption) GetProviderSamlMetadataResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetProviderSamlMetadataResultOutput, error) {
			args := v.(GetProviderSamlMetadataArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetProviderSamlMetadataResult
			secret, err := ctx.InvokePackageRaw("authentik:index/getProviderSamlMetadata:getProviderSamlMetadata", args, &rv, "", opts...)
			if err != nil {
				return GetProviderSamlMetadataResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetProviderSamlMetadataResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetProviderSamlMetadataResultOutput), nil
			}
			return output, nil
		}).(GetProviderSamlMetadataResultOutput)
}

// A collection of arguments for invoking getProviderSamlMetadata.
type GetProviderSamlMetadataOutputArgs struct {
	// Find provider by name
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Find provider by ID
	ProviderId pulumi.IntPtrInput `pulumi:"providerId"`
}

func (GetProviderSamlMetadataOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProviderSamlMetadataArgs)(nil)).Elem()
}

// A collection of values returned by getProviderSamlMetadata.
type GetProviderSamlMetadataResultOutput struct{ *pulumi.OutputState }

func (GetProviderSamlMetadataResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProviderSamlMetadataResult)(nil)).Elem()
}

func (o GetProviderSamlMetadataResultOutput) ToGetProviderSamlMetadataResultOutput() GetProviderSamlMetadataResultOutput {
	return o
}

func (o GetProviderSamlMetadataResultOutput) ToGetProviderSamlMetadataResultOutputWithContext(ctx context.Context) GetProviderSamlMetadataResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetProviderSamlMetadataResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProviderSamlMetadataResult) string { return v.Id }).(pulumi.StringOutput)
}

// SAML Metadata Generated.
func (o GetProviderSamlMetadataResultOutput) Metadata() pulumi.StringOutput {
	return o.ApplyT(func(v GetProviderSamlMetadataResult) string { return v.Metadata }).(pulumi.StringOutput)
}

// Find provider by name
func (o GetProviderSamlMetadataResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetProviderSamlMetadataResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Find provider by ID
func (o GetProviderSamlMetadataResultOutput) ProviderId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetProviderSamlMetadataResult) *int { return v.ProviderId }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProviderSamlMetadataResultOutput{})
}
