// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package authentik

import (
	"context"
	"reflect"

	"github.com/OSMIT-GmbH/pulumi-authentik/sdk/go/authentik/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupTenant(ctx *pulumi.Context, args *LookupTenantArgs, opts ...pulumi.InvokeOption) (*LookupTenantResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupTenantResult
	err := ctx.Invoke("authentik:index/getTenant:getTenant", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTenant.
type LookupTenantArgs struct {
	BrandingFavicon    *string `pulumi:"brandingFavicon"`
	BrandingLogo       *string `pulumi:"brandingLogo"`
	BrandingTitle      *string `pulumi:"brandingTitle"`
	Default            *bool   `pulumi:"default"`
	Domain             *string `pulumi:"domain"`
	EventRetention     *string `pulumi:"eventRetention"`
	FlowAuthentication *string `pulumi:"flowAuthentication"`
	FlowDeviceCode     *string `pulumi:"flowDeviceCode"`
	FlowInvalidation   *string `pulumi:"flowInvalidation"`
	FlowRecovery       *string `pulumi:"flowRecovery"`
	FlowUnenrollment   *string `pulumi:"flowUnenrollment"`
	FlowUserSettings   *string `pulumi:"flowUserSettings"`
	WebCertificate     *string `pulumi:"webCertificate"`
}

// A collection of values returned by getTenant.
type LookupTenantResult struct {
	BrandingFavicon    string `pulumi:"brandingFavicon"`
	BrandingLogo       string `pulumi:"brandingLogo"`
	BrandingTitle      string `pulumi:"brandingTitle"`
	Default            bool   `pulumi:"default"`
	Domain             string `pulumi:"domain"`
	EventRetention     string `pulumi:"eventRetention"`
	FlowAuthentication string `pulumi:"flowAuthentication"`
	FlowDeviceCode     string `pulumi:"flowDeviceCode"`
	FlowInvalidation   string `pulumi:"flowInvalidation"`
	FlowRecovery       string `pulumi:"flowRecovery"`
	FlowUnenrollment   string `pulumi:"flowUnenrollment"`
	FlowUserSettings   string `pulumi:"flowUserSettings"`
	// The provider-assigned unique ID for this managed resource.
	Id             string `pulumi:"id"`
	WebCertificate string `pulumi:"webCertificate"`
}

func LookupTenantOutput(ctx *pulumi.Context, args LookupTenantOutputArgs, opts ...pulumi.InvokeOption) LookupTenantResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupTenantResult, error) {
			args := v.(LookupTenantArgs)
			r, err := LookupTenant(ctx, &args, opts...)
			var s LookupTenantResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupTenantResultOutput)
}

// A collection of arguments for invoking getTenant.
type LookupTenantOutputArgs struct {
	BrandingFavicon    pulumi.StringPtrInput `pulumi:"brandingFavicon"`
	BrandingLogo       pulumi.StringPtrInput `pulumi:"brandingLogo"`
	BrandingTitle      pulumi.StringPtrInput `pulumi:"brandingTitle"`
	Default            pulumi.BoolPtrInput   `pulumi:"default"`
	Domain             pulumi.StringPtrInput `pulumi:"domain"`
	EventRetention     pulumi.StringPtrInput `pulumi:"eventRetention"`
	FlowAuthentication pulumi.StringPtrInput `pulumi:"flowAuthentication"`
	FlowDeviceCode     pulumi.StringPtrInput `pulumi:"flowDeviceCode"`
	FlowInvalidation   pulumi.StringPtrInput `pulumi:"flowInvalidation"`
	FlowRecovery       pulumi.StringPtrInput `pulumi:"flowRecovery"`
	FlowUnenrollment   pulumi.StringPtrInput `pulumi:"flowUnenrollment"`
	FlowUserSettings   pulumi.StringPtrInput `pulumi:"flowUserSettings"`
	WebCertificate     pulumi.StringPtrInput `pulumi:"webCertificate"`
}

func (LookupTenantOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTenantArgs)(nil)).Elem()
}

// A collection of values returned by getTenant.
type LookupTenantResultOutput struct{ *pulumi.OutputState }

func (LookupTenantResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTenantResult)(nil)).Elem()
}

func (o LookupTenantResultOutput) ToLookupTenantResultOutput() LookupTenantResultOutput {
	return o
}

func (o LookupTenantResultOutput) ToLookupTenantResultOutputWithContext(ctx context.Context) LookupTenantResultOutput {
	return o
}

func (o LookupTenantResultOutput) BrandingFavicon() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.BrandingFavicon }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) BrandingLogo() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.BrandingLogo }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) BrandingTitle() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.BrandingTitle }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupTenantResult) bool { return v.Default }).(pulumi.BoolOutput)
}

func (o LookupTenantResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.Domain }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) EventRetention() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.EventRetention }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) FlowAuthentication() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.FlowAuthentication }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) FlowDeviceCode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.FlowDeviceCode }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) FlowInvalidation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.FlowInvalidation }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) FlowRecovery() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.FlowRecovery }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) FlowUnenrollment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.FlowUnenrollment }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) FlowUserSettings() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.FlowUserSettings }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupTenantResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTenantResultOutput) WebCertificate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTenantResult) string { return v.WebCertificate }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTenantResultOutput{})
}
