// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package authentik

import (
	"context"
	"reflect"

	"errors"
	"github.com/OSMIT-GmbH/pulumi-authentik/sdk/go/authentik/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/OSMIT-GmbH/pulumi-authentik/sdk/go/authentik"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := authentik.NewStageAuthenticatorValidate(ctx, "name", &authentik.StageAuthenticatorValidateArgs{
//				DeviceClasses: pulumi.StringArray{
//					pulumi.String("static"),
//				},
//				NotConfiguredAction: pulumi.String("skip"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type StageAuthenticatorValidate struct {
	pulumi.CustomResourceState

	ConfigurationStages pulumi.StringArrayOutput `pulumi:"configurationStages"`
	DeviceClasses       pulumi.StringArrayOutput `pulumi:"deviceClasses"`
	// Defaults to `seconds=0`.
	LastAuthThreshold   pulumi.StringPtrOutput `pulumi:"lastAuthThreshold"`
	Name                pulumi.StringOutput    `pulumi:"name"`
	NotConfiguredAction pulumi.StringOutput    `pulumi:"notConfiguredAction"`
	// Defaults to `preferred`.
	WebauthnUserVerification pulumi.StringPtrOutput `pulumi:"webauthnUserVerification"`
}

// NewStageAuthenticatorValidate registers a new resource with the given unique name, arguments, and options.
func NewStageAuthenticatorValidate(ctx *pulumi.Context,
	name string, args *StageAuthenticatorValidateArgs, opts ...pulumi.ResourceOption) (*StageAuthenticatorValidate, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NotConfiguredAction == nil {
		return nil, errors.New("invalid value for required argument 'NotConfiguredAction'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource StageAuthenticatorValidate
	err := ctx.RegisterResource("authentik:index/stageAuthenticatorValidate:StageAuthenticatorValidate", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStageAuthenticatorValidate gets an existing StageAuthenticatorValidate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStageAuthenticatorValidate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StageAuthenticatorValidateState, opts ...pulumi.ResourceOption) (*StageAuthenticatorValidate, error) {
	var resource StageAuthenticatorValidate
	err := ctx.ReadResource("authentik:index/stageAuthenticatorValidate:StageAuthenticatorValidate", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StageAuthenticatorValidate resources.
type stageAuthenticatorValidateState struct {
	ConfigurationStages []string `pulumi:"configurationStages"`
	DeviceClasses       []string `pulumi:"deviceClasses"`
	// Defaults to `seconds=0`.
	LastAuthThreshold   *string `pulumi:"lastAuthThreshold"`
	Name                *string `pulumi:"name"`
	NotConfiguredAction *string `pulumi:"notConfiguredAction"`
	// Defaults to `preferred`.
	WebauthnUserVerification *string `pulumi:"webauthnUserVerification"`
}

type StageAuthenticatorValidateState struct {
	ConfigurationStages pulumi.StringArrayInput
	DeviceClasses       pulumi.StringArrayInput
	// Defaults to `seconds=0`.
	LastAuthThreshold   pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	NotConfiguredAction pulumi.StringPtrInput
	// Defaults to `preferred`.
	WebauthnUserVerification pulumi.StringPtrInput
}

func (StageAuthenticatorValidateState) ElementType() reflect.Type {
	return reflect.TypeOf((*stageAuthenticatorValidateState)(nil)).Elem()
}

type stageAuthenticatorValidateArgs struct {
	ConfigurationStages []string `pulumi:"configurationStages"`
	DeviceClasses       []string `pulumi:"deviceClasses"`
	// Defaults to `seconds=0`.
	LastAuthThreshold   *string `pulumi:"lastAuthThreshold"`
	Name                *string `pulumi:"name"`
	NotConfiguredAction string  `pulumi:"notConfiguredAction"`
	// Defaults to `preferred`.
	WebauthnUserVerification *string `pulumi:"webauthnUserVerification"`
}

// The set of arguments for constructing a StageAuthenticatorValidate resource.
type StageAuthenticatorValidateArgs struct {
	ConfigurationStages pulumi.StringArrayInput
	DeviceClasses       pulumi.StringArrayInput
	// Defaults to `seconds=0`.
	LastAuthThreshold   pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	NotConfiguredAction pulumi.StringInput
	// Defaults to `preferred`.
	WebauthnUserVerification pulumi.StringPtrInput
}

func (StageAuthenticatorValidateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*stageAuthenticatorValidateArgs)(nil)).Elem()
}

type StageAuthenticatorValidateInput interface {
	pulumi.Input

	ToStageAuthenticatorValidateOutput() StageAuthenticatorValidateOutput
	ToStageAuthenticatorValidateOutputWithContext(ctx context.Context) StageAuthenticatorValidateOutput
}

func (*StageAuthenticatorValidate) ElementType() reflect.Type {
	return reflect.TypeOf((**StageAuthenticatorValidate)(nil)).Elem()
}

func (i *StageAuthenticatorValidate) ToStageAuthenticatorValidateOutput() StageAuthenticatorValidateOutput {
	return i.ToStageAuthenticatorValidateOutputWithContext(context.Background())
}

func (i *StageAuthenticatorValidate) ToStageAuthenticatorValidateOutputWithContext(ctx context.Context) StageAuthenticatorValidateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StageAuthenticatorValidateOutput)
}

func (i *StageAuthenticatorValidate) ToOutput(ctx context.Context) pulumix.Output[*StageAuthenticatorValidate] {
	return pulumix.Output[*StageAuthenticatorValidate]{
		OutputState: i.ToStageAuthenticatorValidateOutputWithContext(ctx).OutputState,
	}
}

// StageAuthenticatorValidateArrayInput is an input type that accepts StageAuthenticatorValidateArray and StageAuthenticatorValidateArrayOutput values.
// You can construct a concrete instance of `StageAuthenticatorValidateArrayInput` via:
//
//	StageAuthenticatorValidateArray{ StageAuthenticatorValidateArgs{...} }
type StageAuthenticatorValidateArrayInput interface {
	pulumi.Input

	ToStageAuthenticatorValidateArrayOutput() StageAuthenticatorValidateArrayOutput
	ToStageAuthenticatorValidateArrayOutputWithContext(context.Context) StageAuthenticatorValidateArrayOutput
}

type StageAuthenticatorValidateArray []StageAuthenticatorValidateInput

func (StageAuthenticatorValidateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StageAuthenticatorValidate)(nil)).Elem()
}

func (i StageAuthenticatorValidateArray) ToStageAuthenticatorValidateArrayOutput() StageAuthenticatorValidateArrayOutput {
	return i.ToStageAuthenticatorValidateArrayOutputWithContext(context.Background())
}

func (i StageAuthenticatorValidateArray) ToStageAuthenticatorValidateArrayOutputWithContext(ctx context.Context) StageAuthenticatorValidateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StageAuthenticatorValidateArrayOutput)
}

func (i StageAuthenticatorValidateArray) ToOutput(ctx context.Context) pulumix.Output[[]*StageAuthenticatorValidate] {
	return pulumix.Output[[]*StageAuthenticatorValidate]{
		OutputState: i.ToStageAuthenticatorValidateArrayOutputWithContext(ctx).OutputState,
	}
}

// StageAuthenticatorValidateMapInput is an input type that accepts StageAuthenticatorValidateMap and StageAuthenticatorValidateMapOutput values.
// You can construct a concrete instance of `StageAuthenticatorValidateMapInput` via:
//
//	StageAuthenticatorValidateMap{ "key": StageAuthenticatorValidateArgs{...} }
type StageAuthenticatorValidateMapInput interface {
	pulumi.Input

	ToStageAuthenticatorValidateMapOutput() StageAuthenticatorValidateMapOutput
	ToStageAuthenticatorValidateMapOutputWithContext(context.Context) StageAuthenticatorValidateMapOutput
}

type StageAuthenticatorValidateMap map[string]StageAuthenticatorValidateInput

func (StageAuthenticatorValidateMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StageAuthenticatorValidate)(nil)).Elem()
}

func (i StageAuthenticatorValidateMap) ToStageAuthenticatorValidateMapOutput() StageAuthenticatorValidateMapOutput {
	return i.ToStageAuthenticatorValidateMapOutputWithContext(context.Background())
}

func (i StageAuthenticatorValidateMap) ToStageAuthenticatorValidateMapOutputWithContext(ctx context.Context) StageAuthenticatorValidateMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StageAuthenticatorValidateMapOutput)
}

func (i StageAuthenticatorValidateMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*StageAuthenticatorValidate] {
	return pulumix.Output[map[string]*StageAuthenticatorValidate]{
		OutputState: i.ToStageAuthenticatorValidateMapOutputWithContext(ctx).OutputState,
	}
}

type StageAuthenticatorValidateOutput struct{ *pulumi.OutputState }

func (StageAuthenticatorValidateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StageAuthenticatorValidate)(nil)).Elem()
}

func (o StageAuthenticatorValidateOutput) ToStageAuthenticatorValidateOutput() StageAuthenticatorValidateOutput {
	return o
}

func (o StageAuthenticatorValidateOutput) ToStageAuthenticatorValidateOutputWithContext(ctx context.Context) StageAuthenticatorValidateOutput {
	return o
}

func (o StageAuthenticatorValidateOutput) ToOutput(ctx context.Context) pulumix.Output[*StageAuthenticatorValidate] {
	return pulumix.Output[*StageAuthenticatorValidate]{
		OutputState: o.OutputState,
	}
}

func (o StageAuthenticatorValidateOutput) ConfigurationStages() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *StageAuthenticatorValidate) pulumi.StringArrayOutput { return v.ConfigurationStages }).(pulumi.StringArrayOutput)
}

func (o StageAuthenticatorValidateOutput) DeviceClasses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *StageAuthenticatorValidate) pulumi.StringArrayOutput { return v.DeviceClasses }).(pulumi.StringArrayOutput)
}

// Defaults to `seconds=0`.
func (o StageAuthenticatorValidateOutput) LastAuthThreshold() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StageAuthenticatorValidate) pulumi.StringPtrOutput { return v.LastAuthThreshold }).(pulumi.StringPtrOutput)
}

func (o StageAuthenticatorValidateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StageAuthenticatorValidate) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o StageAuthenticatorValidateOutput) NotConfiguredAction() pulumi.StringOutput {
	return o.ApplyT(func(v *StageAuthenticatorValidate) pulumi.StringOutput { return v.NotConfiguredAction }).(pulumi.StringOutput)
}

// Defaults to `preferred`.
func (o StageAuthenticatorValidateOutput) WebauthnUserVerification() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StageAuthenticatorValidate) pulumi.StringPtrOutput { return v.WebauthnUserVerification }).(pulumi.StringPtrOutput)
}

type StageAuthenticatorValidateArrayOutput struct{ *pulumi.OutputState }

func (StageAuthenticatorValidateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*StageAuthenticatorValidate)(nil)).Elem()
}

func (o StageAuthenticatorValidateArrayOutput) ToStageAuthenticatorValidateArrayOutput() StageAuthenticatorValidateArrayOutput {
	return o
}

func (o StageAuthenticatorValidateArrayOutput) ToStageAuthenticatorValidateArrayOutputWithContext(ctx context.Context) StageAuthenticatorValidateArrayOutput {
	return o
}

func (o StageAuthenticatorValidateArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*StageAuthenticatorValidate] {
	return pulumix.Output[[]*StageAuthenticatorValidate]{
		OutputState: o.OutputState,
	}
}

func (o StageAuthenticatorValidateArrayOutput) Index(i pulumi.IntInput) StageAuthenticatorValidateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *StageAuthenticatorValidate {
		return vs[0].([]*StageAuthenticatorValidate)[vs[1].(int)]
	}).(StageAuthenticatorValidateOutput)
}

type StageAuthenticatorValidateMapOutput struct{ *pulumi.OutputState }

func (StageAuthenticatorValidateMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*StageAuthenticatorValidate)(nil)).Elem()
}

func (o StageAuthenticatorValidateMapOutput) ToStageAuthenticatorValidateMapOutput() StageAuthenticatorValidateMapOutput {
	return o
}

func (o StageAuthenticatorValidateMapOutput) ToStageAuthenticatorValidateMapOutputWithContext(ctx context.Context) StageAuthenticatorValidateMapOutput {
	return o
}

func (o StageAuthenticatorValidateMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*StageAuthenticatorValidate] {
	return pulumix.Output[map[string]*StageAuthenticatorValidate]{
		OutputState: o.OutputState,
	}
}

func (o StageAuthenticatorValidateMapOutput) MapIndex(k pulumi.StringInput) StageAuthenticatorValidateOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *StageAuthenticatorValidate {
		return vs[0].(map[string]*StageAuthenticatorValidate)[vs[1].(string)]
	}).(StageAuthenticatorValidateOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StageAuthenticatorValidateInput)(nil)).Elem(), &StageAuthenticatorValidate{})
	pulumi.RegisterInputType(reflect.TypeOf((*StageAuthenticatorValidateArrayInput)(nil)).Elem(), StageAuthenticatorValidateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*StageAuthenticatorValidateMapInput)(nil)).Elem(), StageAuthenticatorValidateMap{})
	pulumi.RegisterOutputType(StageAuthenticatorValidateOutput{})
	pulumi.RegisterOutputType(StageAuthenticatorValidateArrayOutput{})
	pulumi.RegisterOutputType(StageAuthenticatorValidateMapOutput{})
}
