// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getProviderSamlMetadata(args?: GetProviderSamlMetadataArgs, opts?: pulumi.InvokeOptions): Promise<GetProviderSamlMetadataResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getProviderSamlMetadata:getProviderSamlMetadata", {
        "name": args.name,
        "providerId": args.providerId,
    }, opts);
}

/**
 * A collection of arguments for invoking getProviderSamlMetadata.
 */
export interface GetProviderSamlMetadataArgs {
    name?: string;
    providerId?: number;
}

/**
 * A collection of values returned by getProviderSamlMetadata.
 */
export interface GetProviderSamlMetadataResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly metadata: string;
    readonly name?: string;
    readonly providerId?: number;
}
export function getProviderSamlMetadataOutput(args?: GetProviderSamlMetadataOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetProviderSamlMetadataResult> {
    return pulumi.output(args).apply((a: any) => getProviderSamlMetadata(a, opts))
}

/**
 * A collection of arguments for invoking getProviderSamlMetadata.
 */
export interface GetProviderSamlMetadataOutputArgs {
    name?: pulumi.Input<string>;
    providerId?: pulumi.Input<number>;
}
