// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get SAML Provider Property mappings
 */
export function getPropertyMappingProviderSaml(args?: GetPropertyMappingProviderSamlArgs, opts?: pulumi.InvokeOptions): Promise<GetPropertyMappingProviderSamlResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getPropertyMappingProviderSaml:getPropertyMappingProviderSaml", {
        "expression": args.expression,
        "friendlyName": args.friendlyName,
        "ids": args.ids,
        "managed": args.managed,
        "managedLists": args.managedLists,
        "name": args.name,
        "samlName": args.samlName,
    }, opts);
}

/**
 * A collection of arguments for invoking getPropertyMappingProviderSaml.
 */
export interface GetPropertyMappingProviderSamlArgs {
    /**
     * Generated.
     */
    expression?: string;
    /**
     * Generated.
     */
    friendlyName?: string;
    /**
     * List of ids when `managedList` is set. Generated.
     */
    ids?: string[];
    managed?: string;
    /**
     * Retrieve multiple property mappings
     */
    managedLists?: string[];
    name?: string;
    /**
     * Generated.
     */
    samlName?: string;
}

/**
 * A collection of values returned by getPropertyMappingProviderSaml.
 */
export interface GetPropertyMappingProviderSamlResult {
    /**
     * Generated.
     */
    readonly expression: string;
    /**
     * Generated.
     */
    readonly friendlyName: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of ids when `managedList` is set. Generated.
     */
    readonly ids: string[];
    readonly managed?: string;
    /**
     * Retrieve multiple property mappings
     */
    readonly managedLists?: string[];
    readonly name?: string;
    /**
     * Generated.
     */
    readonly samlName: string;
}
/**
 * Get SAML Provider Property mappings
 */
export function getPropertyMappingProviderSamlOutput(args?: GetPropertyMappingProviderSamlOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPropertyMappingProviderSamlResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getPropertyMappingProviderSaml:getPropertyMappingProviderSaml", {
        "expression": args.expression,
        "friendlyName": args.friendlyName,
        "ids": args.ids,
        "managed": args.managed,
        "managedLists": args.managedLists,
        "name": args.name,
        "samlName": args.samlName,
    }, opts);
}

/**
 * A collection of arguments for invoking getPropertyMappingProviderSaml.
 */
export interface GetPropertyMappingProviderSamlOutputArgs {
    /**
     * Generated.
     */
    expression?: pulumi.Input<string>;
    /**
     * Generated.
     */
    friendlyName?: pulumi.Input<string>;
    /**
     * List of ids when `managedList` is set. Generated.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    managed?: pulumi.Input<string>;
    /**
     * Retrieve multiple property mappings
     */
    managedLists?: pulumi.Input<pulumi.Input<string>[]>;
    name?: pulumi.Input<string>;
    /**
     * Generated.
     */
    samlName?: pulumi.Input<string>;
}
