// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get Source by name, slug or managed
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as authentik from "@pulumi/authentik";
 *
 * const inbuilt = authentik.getSource({
 *     managed: "goauthentik.io/sources/inbuilt",
 * });
 * ```
 */
export function getSource(args?: GetSourceArgs, opts?: pulumi.InvokeOptions): Promise<GetSourceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getSource:getSource", {
        "managed": args.managed,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getSource.
 */
export interface GetSourceArgs {
    /**
     * Generated.
     */
    managed?: string;
    /**
     * Generated.
     */
    slug?: string;
}

/**
 * A collection of values returned by getSource.
 */
export interface GetSourceResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Generated.
     */
    readonly managed: string;
    /**
     * Generated.
     */
    readonly name: string;
    /**
     * Generated.
     */
    readonly slug: string;
    /**
     * Generated.
     */
    readonly uuid: string;
}
/**
 * Get Source by name, slug or managed
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as authentik from "@pulumi/authentik";
 *
 * const inbuilt = authentik.getSource({
 *     managed: "goauthentik.io/sources/inbuilt",
 * });
 * ```
 */
export function getSourceOutput(args?: GetSourceOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSourceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getSource:getSource", {
        "managed": args.managed,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getSource.
 */
export interface GetSourceOutputArgs {
    /**
     * Generated.
     */
    managed?: pulumi.Input<string>;
    /**
     * Generated.
     */
    slug?: pulumi.Input<string>;
}
