// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get users by pk or username
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as authentik from "@pulumi/authentik";
 *
 * // To get the name of a user by username
 * const akadmin = authentik.getUser({
 *     username: "akadmin",
 * });
 * ```
 */
export function getUser(args?: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getUser:getUser", {
        "pk": args.pk,
        "username": args.username,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    /**
     * Generated.
     */
    pk?: number;
    /**
     * Generated.
     */
    username?: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    /**
     * Generated.
     */
    readonly attributes: string;
    /**
     * Generated.
     */
    readonly avatar: string;
    /**
     * Generated.
     */
    readonly email: string;
    /**
     * Generated.
     */
    readonly groups: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Generated.
     */
    readonly isActive: boolean;
    /**
     * Generated.
     */
    readonly isSuperuser: boolean;
    /**
     * Generated.
     */
    readonly lastLogin: string;
    /**
     * Generated.
     */
    readonly name: string;
    /**
     * Generated.
     */
    readonly path: string;
    /**
     * Generated.
     */
    readonly pk: number;
    /**
     * Generated.
     */
    readonly type: string;
    /**
     * Generated.
     */
    readonly uid: string;
    /**
     * Generated.
     */
    readonly username: string;
    /**
     * Generated.
     */
    readonly uuid: string;
}
/**
 * Get users by pk or username
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as authentik from "@pulumi/authentik";
 *
 * // To get the name of a user by username
 * const akadmin = authentik.getUser({
 *     username: "akadmin",
 * });
 * ```
 */
export function getUserOutput(args?: GetUserOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetUserResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getUser:getUser", {
        "pk": args.pk,
        "username": args.username,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
    /**
     * Generated.
     */
    pk?: pulumi.Input<number>;
    /**
     * Generated.
     */
    username?: pulumi.Input<string>;
}
